import type { Metadata } from "next";
import { Source_Sans_3 as SourceSans3 } from "next/font/google";
import type { ReactNode } from "react";

import resolveClassNames from "@/lib/resolveClassNames";

import "./globals.css";

export default function RootLayout(props: Readonly<RootLayoutProps>) {
  const { children } = props;
  const className = resolveClassNames("antialiased", sourceSans.className);

  return (
    <html lang="en">
      <body className={className}>{children}</body>
    </html>
  );
}

export interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sourceSans = SourceSans3({ subsets: ["latin"] });
