import type { Metadata } from "next";
import { Source_Sans_3 as SourceSans3 } from "next/font/google";
import type { ReactNode } from "react";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import * as content from "@/lib/content";
import resolveClassNames from "@/lib/resolveClassNames";

import "./globals.css";

export default async function RootLayout(props: Readonly<RootLayoutProps>) {
  const { children } = props;
  const className = resolveClassNames("antialiased", sourceSans.className);

  const siteMetadata = await content.getJsonByTitle("Site Metadata");
  const { author } = siteMetadata;

  const siteConfiguration = await content.getJsonByTitle("Site Configuration");
  const { amiLogoId, cmiLogoId, copyrightYear, siteLogoId } = siteConfiguration;
  const amiLogoData = await content.getImageData(amiLogoId);
  const cmiLogoData = await content.getImageData(cmiLogoId);
  const siteLogoData = await content.getImageData(siteLogoId);

  return (
    <html lang="en">
      <body className={className}>
        <Header className="mb-8 mt-4 mx-4" logoData={siteLogoData} />
        <main className="container mx-auto">{children}</main>
        <Footer
          amiLogoData={amiLogoData}
          className="mb-4 mt-8 mx-4"
          cmiLogoData={cmiLogoData}
          copyrightHolder={author}
          copyrightYear={copyrightYear}
          currentYear={currentYear}
        />
      </body>
    </html>
  );
}

export interface RootLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const currentYear = new Date().getFullYear();
const sourceSans = SourceSans3({ subsets: ["latin"] });
