name: Deployment
on:
  release:
    types: [released]
  workflow_dispatch:
concurrency:
  group: deployment
  cancel-in-progress: true
env:
  CONTACT_RECIPIENT_EMAIL: ${{ secrets.CONTACT_RECIPIENT_EMAIL }}
  CONTACT_SENDER_EMAIL: ${{ secrets.CONTACT_SENDER_EMAIL }}
  CONTACT_SENDER_NAME: ${{ vars.CONTACT_SENDER_NAME }}
  CONTENTFUL_ASSET_CDN_HOSTNAME: ${{vars.CONTENTFUL_ASSET_CDN_HOSTNAME}}
  CONTENTFUL_IMAGE_CDN_HOSTNAME: ${{vars.CONTENTFUL_IMAGE_CDN_HOSTNAME}}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Unit and Integration Tests
        run: npm run test
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_DEVELOPMENT }}
          CONTENTFUL_ENVIRONMENT: ${{ vars.CONTENTFUL_ENVIRONMENT_DEVELOPMENT }}
      - name: Deploy Staging
        id: deploy-staging
        uses: amondnet/vercel-action@v25
        with:
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: |
            -b CONTACT_RECIPIENT_EMAIL=${{ secrets.CONTACT_RECIPIENT_EMAIL }}
            -b CONTACT_SENDER_EMAIL=${{ secrets.CONTACT_SENDER_EMAIL }}
            -b "CONTACT_SENDER_NAME=${{ vars.CONTACT_SENDER_NAME }}"
            -b CONTENTFUL_ACCESS_TOKEN=${{secrets.CONTENTFUL_ACCESS_TOKEN_PRODUCTION}}
            -b CONTENTFUL_ASSET_CDN_HOSTNAME=${{vars.CONTENTFUL_ASSET_CDN_HOSTNAME}}
            -b CONTENTFUL_ENVIRONMENT=${{vars.CONTENTFUL_ENVIRONMENT_PRODUCTION}}
            -b CONTENTFUL_IMAGE_CDN_HOSTNAME=${{vars.CONTENTFUL_IMAGE_CDN_HOSTNAME}}
            -b CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}
            -b SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
