name: Publish
on:
  repository_dispatch:
    types: [publish]
  workflow_dispatch:
concurrency:
  group: deployment
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Last Successful Deployment SHA
        id: get-last-successful-deployment-sha
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/get-latest-release-tag.js');
            const result = await script({context, core, github});
            console.log(result);
            return result;
        # env:
        #   ENVIRONMENT: production
      - name: Checkout Ref
        uses: actions/checkout@v4
        with:
          ref: "v1.0.3"
      - name: Setup
        uses: ./.github/actions/setup
      # - name: Deploy Production
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     scope: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-args: |
      #       --prod
      #       -b CONTENTFUL_ACCESS_TOKEN=${{secrets.CONTENTFUL_ACCESS_TOKEN_PRODUCTION}}
      #       -b CONTENTFUL_ASSET_CDN_HOSTNAME=${{vars.CONTENTFUL_ASSET_CDN_HOSTNAME}}
      #       -b CONTENTFUL_ENVIRONMENT=${{vars.CONTENTFUL_ENVIRONMENT_PRODUCTION}}
      #       -b CONTENTFUL_IMAGE_CDN_HOSTNAME=${{vars.CONTENTFUL_IMAGE_CDN_HOSTNAME}}
      #       -b CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
